config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  resources :tasks, except: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
	validates_presence_of :title
	validate :future_completed_date

	private

	def future_completed_date
		if !completed.blank? && completed > Date.today
			self.errors.add(:completed, "can't be in the future")
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		@tasks = Task.all
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def new
		@task = Task.new
		render :show_form
	end

	def create
		@task = Task.new(task_params)
		save_task
	end

	def destroy
		@task = Task.find(params[:id])
		@task.destroy
		@tasks=Task.all
	end

	def edit
		@task = Task.find(params[:id])
		render :show_form
	end

	def update
		@task = Task.find(params[:id])
		@task.update_attributes(task_params)
		save_task
	end

	private
	def task_params
		params.require(:task).permit(:title, :note, :completed)
	end

	def save_task
		if @task.save
			@tasks = Task.all
			render :hide_form
		else
			render :show_form
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="row-fluid">
      <div class="span10 offset1">
        <div class="hero-unit text-center">
          <h1>ToDo</h1>
          <p>Welcome to the ToDo app</p>
          <%= link_to 'New task', new_task_path, class: 'btn btn-primary', remote: true %>
          <div id="modal">
    
          </div>
        </div>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="task-list" class="container">
	<%= render partial: 'tasks/task_list', locals: {tasks: @tasks} %>
</div>
<div id="modal" class="modal fade"></div>

app/views/tasks/_task_form.html.erb
<div class="modal-header">
	<h1>
		<%= task.new_record? ? 'New Task' : "Editing task #{task.title}" %>
	</h1>
</div>
<%= simple_form_for task, class: 'clearfix', remote: true do |f| %>
	<div class="modal-body">
		<%= f.input :title %>
		<%= f.input :note %>
		<%= f.input :completed %>
	</div>
	<div class="modal-footer">
		<%= f.submit 'Save', class: 'btn btn-primary' %>
		<button id="cancel" class='btn btn-secondary'>Cancel</button>
	</div>
	
<% end %>

app/views/tasks/_task_list.html.erb
<% if tasks.empty? %>
	<span class="text-warning">There are no tasks!</span>
<% else %>
	<table class="table table-hover">
		<tr>
			<th>ToDo</th>
			<th>Created at</th>
			<th>Completed at</th>
			<th>Actions</th>
		</tr>
		<% tasks.each do |task| %>
			<tr>
				<td>
					<strong><%= task.title %></strong>
				</td>
				<td class="text-info">
					<%= task.created_at %>
				</td>
				<td class="text-success">
					<%= task.completed %>
				</td>
				<td>
					<%= link_to task_path(task), remote: true, method: :delete, data: {confirm: "Are you sure you want to delete #{task.title}?"} do %> X
					 <% end %>
					<%= link_to edit_task_path(task), remote: true do %> E
					<% end %>
				</td>
			</tr>
		<% end %>
	</table>
<% end %>

app/views/tasks/destroy.js.erb
$('#task-list').html('<%= j(render partial: 'task_list', locals: {tasks: @tasks})%>');

app/views/tasks/hide_form.erb
$('#task-list').html('<%= j(render partial: 'tasks/task_list', locals: {tasks: @tasks}) %>');
$('#modal').html('');

app/views/tasks/new.js.erb
$( document ).ready(function() {
    console.log( "ready!" );

m = $('#modal');
m.html('<%= j(render partial: 'task_form', locals: {task: @task}) %>');
	$('#cancel').click(function(){
		m.html('');
	})
});

app/views/tasks/show_form.js.erb
$( document ).ready(function() {
    console.log( "ready!" );

m = $('#modal');
m.html('<%= j(render partial: 'task_form', locals: {task: @task}) %>');
	$('#cancel').click(function(){
		m.html('');
	})
});